Feature/aks guide
distributed-technologies/yggdrasil pull request #58
Opened 2022-01-12 06:43 UTC by jaxels10

I have added the documentation for creating an aks cluster and deploying the platform onto it. This is an initial guide on how to do it, and is subject to change in the future. I have also added the ARM template for creating the aks cluster.

2022-01-12 13:39 UTC, klausenbusk commented on README.md
> +# Deploy the platform for development
Let be specific here. This is just *one* way to deploy a development cluster.
```suggestion
# Deploy the platform for development on Azure
```

Also this is the first use of the word "platform". It should be explained in the README I think or `s/platform/Yggdrasil/`.

2022-01-12 13:39 UTC, klausenbusk commented on README.md
> +You now have access to your new Kubernetes development environment. The next thing we need to do is deploy the SCCP platform onto the cluster. Since we are using AKS, it will not be the whole SCCP pl
This is the first time SCCP is mentioned in the README, so just suddenly mentioning it, is a bit odd.
```suggestion
You now have access to your new Kubernetes development environment. The next thing we need to do is deploy Yggdrasil onto the cluster.
```
Perhaps?

2022-01-12 13:39 UTC, klausenbusk commented on nidhogg/values.yaml
> +  # Whether to install the container network interface on the cluster. Should be false when installed on AKS
```suggestion
  # Whether to install the container network interface on the cluster. Should be false when using a managed Kubernetes solution (ex: Azure's AKS)
```

2022-01-12 18:58 UTC, skovbakke commented on README.md
> +You are now ready to install Yggdrasil on the cluster by running the command:
When do they clone Yggdrasil and commit their values in git? Should this not be a part of the guide, or are we doing the classic "look how easy it is get started and deploy non-configured" and afterwards ask them to clone + configure? In that case, we could skip the process of editing values at this point, just deploy our standard _everything false_ configuration and get them to the green checkmark sooner.

2022-01-12 19:57 UTC, skovbakke requested changes

2022-01-12 19:57 UTC, skovbakke commented on yggdrasil/services/rook-ceph/ceph/ceph.yaml
> +                    - rook-ceph-osd-prepare
Maybe it would be nicer to replace these `matchExpressions` with [`matchLabels`](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#labelselector-v1-meta), e.g.
```suggestion
                  matchLabels:
                    app: rook-ceph-osd
                    app: rook-ceph-osd-prepare
```
Now, looking at the suggestion I just made, it is clear that that will not work... `app` can not have two values. We need to rework this as it is also a problem in the current form: the `matchExpressions` are ANDed (see above link). Basically, right now it does nothing because it will not match any pod.

2022-01-12 20:00 UTC, skovbakke commented on yggdrasil/services/rook-ceph/ceph/ceph.yaml
> +                    - rook-ceph-osd-prepare
Well, I think the solution is
```suggestion
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - rook-ceph-osd
                    - rook-ceph-osd-prepare
```

2022-01-12 20:02 UTC, skovbakke commented on yggdrasil/services/rook-ceph/ceph/ceph.yaml
> +                    - rook-ceph-osd-prepare
Looking again I think the solution is simply:
```suggestion
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - rook-ceph-osd
                    - rook-ceph-osd-prepare
```

2022-01-12 20:50 UTC, jaxels10 commented on README.md
> +You can create a development environment that uses Yggdrasil. This development environment will consist of 3 nodes and 3 storage nodes that together form an AKS cluster.
The point to have 3 seperate storage nodes is that nothing other than rook/ceph related resources are ever assigned to the storage nodes.

2022-01-14 08:12 UTC, jaxels10 commented on README.md
> +You are now ready to install Yggdrasil on the cluster by running the command:
Changed it.

2022-01-14 08:14 UTC, jaxels10 commented on README.md
> +Once you have the password, you need to change the service to a loadbalancer and let Azure create a loadbalancer for you. This will create a public IP, which you can use to access the ArgoCD dashboar
This will be future work

2022-01-14 08:29 UTC, jaxels10 commented on README.md
> +You are now ready to install Yggdrasil on the cluster by running the command:
I have addressed this in my newest commit, explaining that you need to push Yggdrasil to your own repository and change the values to point to that.

2022-01-14 08:44 UTC, jaxels10 commented on yggdrasil/services/rook-ceph/ceph/ceph.yaml
> +                    - rook-ceph-osd-prepare
I have implemented this change in my latest commit.

2022-01-17 09:30 UTC, jacobcrawford submitted a review, later dismissed
I can not quite get the installation of yggdrasil to work. I use the branch: 
https://github.com/distributed-technologies/yggdrasil/tree/feature/review-aks-guide

2022-01-17 09:30 UTC, jacobcrawford commented on README.md
> +You are now ready to install Yggdrasil on the cluster by running this command:
We need to run 'helm dependency update nidhogg/' before we are ready to install

2022-01-17 09:30 UTC, jacobcrawford commented on README.md
> +kubectl -n yggdrasil get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d
I don't have this secret. The ones I have:
![image](https://user-images.githubusercontent.com/22328547/149742219-d1408598-00e2-4899-a33b-dce7c8945c87.png)

2022-01-17 09:30 UTC, jacobcrawford commented on README.md
> +To set any cluster configurations, you should edit the nidhogg/values.yaml file. Once you are satisfied with the configurations of the cluster, edit the yggdrasil/values.yaml file and enable the serv
Do we need to configure ingress? When I install nidhogg the ArgoCDServer throvs this error:
![image](https://user-images.githubusercontent.com/22328547/149742997-992c2915-d74c-48cc-b41c-dd453a6c594c.png)

2022-01-18 06:40 UTC, skovbakke approved these changes

2022-01-18 06:41 UTC, skovbakke commented
I approve on the condition that @jacobcrawford is happy as well 🥳

2022-01-21 08:57 UTC, jaxels10 commented on README.md
> +You are now ready to install Yggdrasil on the cluster by running this command:
I have added this to the docs

2022-01-21 09:01 UTC, jaxels10 commented on README.md
> +kubectl -n yggdrasil get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d
I have added how to generate this secret to the documentation

2022-01-21 09:01 UTC, jaxels10 commented on README.md
> +To set any cluster configurations, you should edit the nidhogg/values.yaml file. Once you are satisfied with the configurations of the cluster, edit the yggdrasil/values.yaml file and enable the serv
I am making a change to lightvessel so that we dont have to do this

2022-01-21 21:36 UTC, skovbakke reviewed
I am happy with the wording. If @jacobcrawford has tested it out and it works, then LGTM

2022-01-24 08:44 UTC, jacobcrawford commented
Maybe we should update the lightvessel version so that we can disable Ingress.

2022-01-24 10:21 UTC, klausenbusk submitted a review, later dismissed
@jacobcrawford says it work™ so LGTM 🎉

2022-01-24 10:44 UTC, klausenbusk commented
@jacobcrawford still says it work™ so LGTM 🎉

2022-01-24 10:46 UTC, jacobcrawford approved these changes
After much blood, sweat, and tears this LGTM🎉

2022-01-24 10:48 UTC, klausenbusk approved these changes
@jacobcrawford still says it work™ so LGTM 🎉

2022-01-24 10:48 UTC, merged