Feature/observability stack enable
distributed-technologies/yggdrasil pull request #68
Opened 2022-02-21 14:15 UTC by jacobcrawford

2022-02-21 14:19 UTC, MadsHT commented
Good initiative, But since there are a lot of values that's needed to run tempo and cortex with ceph, I would prefere that this is not merged yet, until we've resolved the ceph-bucket problem.

2022-02-24 09:44 UTC, klausenbusk commented on yggdrasil/services/monitoring/tempo/tempo.yaml
> +            key: BUCKET_REGION
Can't we set them in `config`?

https://github.com/grafana/helm-charts/tree/652c984229db23edd62446447ebfb2d997f5d0e5/charts/tempo-distributed#example-configuration-using-s3-for-storage

2022-02-24 09:48 UTC, MadsHT commented on yggdrasil/services/monitoring/tempo/tempo.yaml
> +            key: BUCKET_REGION
We are just [here](https://github.com/distributed-technologies/yggdrasil/blob/932aa0dea18f2593c0cdb3a4179dd5a7927adfdd/yggdrasil/services/monitoring/tempo/tempo.yaml#L183-L212) instead, since you still have to mount the variables to the pod that's using it in their configs.

This code just mounts the values from the configMap and secret as env variables on the pod

2022-02-24 09:55 UTC, klausenbusk commented on yggdrasil/services/monitoring/tempo/tempo.yaml
> +            key: BUCKET_REGION
Can we do:
```suggestion
    extraEnv:
      envFrom:
      - secretRef:
          name: tempo-bucket-claim
      - configMapRef:
          name: tempo-bucket-claim
```
and perhaps move it `_helpers.tpl`, so we can define the section once and reuse?

2022-02-24 10:11 UTC, MadsHT commented on yggdrasil/services/monitoring/tempo/tempo.yaml
> +            key: BUCKET_REGION
That could work in tempo, since they have value called `extraEnvFrom` [here](https://github.com/grafana/helm-charts/blob/652c984229db23edd62446447ebfb2d997f5d0e5/charts/tempo-distributed/templates/distributor/deployment-distributor.yaml#L95-L99).

This will not work in cortex since they've only mapped the env value [here](https://github.com/cortexproject/cortex-helm-chart/blob/ad2f5cf3ce961af813fc73b9530be75a585322ac/templates/distributor/distributor-dep.yaml#L93) 

Plus I prefer to explicit state what env variables I want.

I had not thought about moving it to a _helper.tpl, which would make it a lot neater, I would like to do that, but keep the explicit value declaration, thoughts?

2022-02-24 11:11 UTC, jaxels10 commented
Should we add a description to this PR? @jacobcrawford 

Also, has this been tested on a cluster and the services all show healthy and synces + we can see data from Cortex in Grafana?

2022-02-24 11:18 UTC, MadsHT commented
I have merged this branch with my `mht-dev` branch to avoid changing settings, and it's all green 👍 
![image](https://user-images.githubusercontent.com/31923273/155514400-50f98573-7406-4702-a297-5fed227cdde9.png)

And there is data in Cortex, looking through Grafana:
![image](https://user-images.githubusercontent.com/31923273/155514140-35805280-9b4a-44cc-aab0-062d7ec7c3f3.png)

2022-02-24 11:44 UTC, klausenbusk commented
Do we get any data from the grafana agents?

2022-02-24 11:48 UTC, MadsHT commented
> Do we get any data from the grafana agents?

Depends on what you mean, All metrics are collected by the Grafana agents and written to Cortex.

But we do not have any metrics on the agents themself, but that can be enabled [here](https://grafana.com/docs/agent/latest/configuration/integrations/#integrations_config), which I think we should do when we set up the other exporters (node and kafka mainly)

2022-02-24 11:52 UTC, klausenbusk commented
> But we do not have any metrics on the agents themself, but that can be enabled [here](https://grafana.com/docs/agent/latest/configuration/integrations/#integrations_config), which I think we should do when we set up the other exporters (node and kafka mainly)

I think we should also enable https://grafana.com/docs/agent/latest/configuration/integrations/integrations-next/eventhandler-config/ (when you get to it).

2022-02-24 11:53 UTC, MadsHT commented
> > But we do not have any metrics on the agents themself, but that can be enabled [here](https://grafana.com/docs/agent/latest/configuration/integrations/#integrations_config), which I think we should do when we set up the other exporters (node and kafka mainly)
> 
> I think we should also enable https://grafana.com/docs/agent/latest/configuration/integrations/integrations-next/eventhandler-config/ (when you get to it).

Agreed 👍

2022-02-24 12:13 UTC, jaxels10 reviewed
Generally looks good, a couple of comments

2022-02-24 12:13 UTC, jaxels10 commented on yggdrasil/services/monitoring/cortex/cortex.yaml
> +      storageClass: ceph-filesystem
Why do we choose to use the ceph-filesystem storageclass for PVCs? Should we not try to use the block storage storageclass for that and then reserve the filesystem for when multiple applications need to store and access the same files? Or perhaps it does not matter? Maybe we should have a discussion about it.

2022-02-24 12:13 UTC, jaxels10 commented on yggdrasil/services/monitoring/grafana-agent/grafana-agent.yaml
> +# This is a values file
Remove this comment once a value has been put into the values file

2022-02-24 12:42 UTC, MadsHT commented on yggdrasil/services/monitoring/cortex/cortex.yaml
> +      storageClass: ceph-filesystem
Well the PVC is enabled by default and I was unsure if the ceph-filesystem was needed for PVCs to work, so I just added it.
If non is given it uses the default provisioner.
[source](https://github.com/cortexproject/cortex-helm-chart/blob/ad2f5cf3ce961af813fc73b9530be75a585322ac/values.yaml#L1229-L1255)

2022-02-28 07:06 UTC, jaxels10 commented on yggdrasil/services/monitoring/cortex/cortex.yaml
> +      storageClass: ceph-filesystem
At the moment, we have made the ceph-filesystem the default storage class. I am, however, unsure that this is what we would like. I believe rook traditionally has the ceph-block-storage as the default storage class and you will then have to specify if you would like to use the distributed file system. Perhaps we should change that default? Ill start a discussion in our dev chat

2022-02-28 07:29 UTC, jaxels10 approved these changes
LGTM

2022-02-28 08:00 UTC, skovbakke requested changes
In general I think we could remove maybe 90% of the comments. I do not think we should explain what the options do, as that is explained in de values file we overwrite, but instead we should explain why we have the specific value, if it makes sense to do so.

2022-02-28 09:39 UTC, jaxels10 submitted a review, later dismissed
LGTM

2022-02-28 10:01 UTC, skovbakke commented on yggdrasil/templates/_helper.tpl
> +- name: AWS_ACCESS_KEY_ID
Currently both blocks we define start with a newline. When we include then you use `indent`. We could also have the block not include a newline at the start and then use `nindent` when we include it.

Which is the preferred way of doing it in helm?

2022-02-28 10:10 UTC, MadsHT commented on yggdrasil/templates/_helper.tpl
> +- name: AWS_ACCESS_KEY_ID
From what I can tell from the helm doc [here](https://helm.sh/docs/chart_template_guide/control_structures/#controlling-whitespace) the dash to the left should remove the whitespace.

2022-02-28 10:38 UTC, skovbakke submitted a review, later dismissed
LGTM 🥳

2022-02-28 11:02 UTC, skovbakke approved these changes
LGTM 🥳

2022-02-28 11:26 UTC, jaxels10 approved these changes
LGTM

2022-02-28 11:47 UTC, merged