Add exporters chart
distributed-technologies/yggdrasil pull request #77
Opened 2022-03-07 08:06 UTC by jaxels10

Add logic to only enable service monitors when prometheus is installed
Add logic to only enable kafka exporter when kafka is installed

This PR enabled the functionality from distributed-technologies/helm-charts/pull/280

2022-03-07 08:23 UTC, MadsHT requested changes
The description and commit message, says that the Kafka exporter is only enabled when Kafka is enabled, but it also requires Prometheus to be enabled.

So to be really pedantic, could we reword those to say that Kafka and Prometheus has to be enabled?

2022-03-07 11:36 UTC, jaxels10 commented
> The description and commit message, says that the Kafka exporter is only enabled when Kafka is enabled, but it also requires Prometheus to be enabled.
> 
> So to be really pedantic, could we reword those to say that Kafka and Prometheus has to be enabled?

You are right and I have now changed this :)

2022-03-07 13:09 UTC, klausenbusk approved these changes
LGTM 🎉

2022-03-07 13:13 UTC, MadsHT approved these changes
LGTM

2022-03-07 14:08 UTC, skovbakke commented
LGTM, Can we merge this?

2022-03-07 15:28 UTC, klausenbusk commented on nidhogg/Chart.yaml
> +version: 2.0.20
```suggestion
version: 2.0.21
```

2022-03-07 15:28 UTC, skovbakke submitted a review, later dismissed
Version bump needed.

2022-03-08 07:14 UTC, jaxels10 commented
@MadsHT merging is blocked due to change request
I have bumped the versions now :-) @klausenbusk @skovbakke

2022-03-08 07:16 UTC, klausenbusk approved these changes
LGTM 🎉

2022-03-08 07:17 UTC, merged